#
# FICHIER ADAPTÉ : docker-compose.yml (Version pour Jenkins)
#
version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: smartphoneDB
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    # L'image est maintenant définie par une variable que Jenkins fournira
    image: ${IMAGE_BACKEND}
    container_name: backend
    restart: always
    # Jenkins va créer un fichier .env.backend temporaire et sécurisé
    env_file:
      - ./.env.backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    # L'image est aussi définie par une variable Jenkins
    image: ${IMAGE_FRONTEND}
    container_name: frontend
    restart: always
    ports:
      # J'ai gardé ton port 8080
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data:
